import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const generateContractPDF = async (contract) => {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
          .header { text-align: center; border-bottom: 2px solid #4CAF50; padding-bottom: 20px; margin-bottom: 30px; }
          .title { font-size: 24px; font-weight: bold; color: #4CAF50; margin-bottom: 5px; }
          .contract-id { font-size: 14px; color: #666; }
          .section { margin-bottom: 25px; }
          .section-title { font-size: 18px; font-weight: bold; border-left: 4px solid #4CAF50; padding-left: 10px; margin-bottom: 15px; }
          .row { display: flex; justify-content: space-between; margin-bottom: 10px; }
          .label { font-weight: bold; color: #555; }
          .value { color: #000; }
          .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 12px; color: #999; text-align: center; }
          .signatures { display: flex; justify-content: space-between; margin-top: 60px; }
          .sig-box { width: 200px; border-top: 1px solid #333; text-align: center; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">AGRICULTURAL SALES CONTRACT</div>
          <div class="contract-id">ID: ${contract.id}</div>
          <div class="date">Date: ${new Date(contract.createdAt).toLocaleDateString()}</div>
        </div>

        <div class="section">
          <div class="section-title">Parties</div>
          <div class="row">
            <div class="sig-box">
              <span class="label">Farmer (Seller):</span><br/>
              <span class="value">${contract.farmerName}</span>
            </div>
            <div class="sig-box">
              <span class="label">Buyer (Purchaser):</span><br/>
              <span class="value">${contract.buyerName}</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Commodity Details</div>
          <div class="row"><span class="label">Crop Name:</span><span class="value">${contract.cropName}</span></div>
          <div class="row"><span class="label">Quantity:</span><span class="value">${contract.quantity} kg</span></div>
          <div class="row"><span class="label">Agreed Price:</span><span class="value">₹${contract.agreedPrice}/kg</span></div>
          <div class="row"><span class="label">Total Value:</span><span class="value" style="font-size: 18px; font-weight: bold;">₹${contract.totalAmount}</span></div>
        </div>

        <div class="section">
          <div class="section-title">Payment & Delivery</div>
          <div class="row"><span class="label">Advance Payment:</span><span class="value">₹${contract.advanceAmount}</span></div>
          <div class="row"><span class="label">Balance Payment:</span><span class="value">₹${contract.remainingAmount}</span></div>
          <div class="row"><span class="label">Expected Delivery Date:</span><span class="value">${new Date(contract.deliveryDate).toLocaleDateString()}</span></div>
          <div class="row"><span class="label">Delivery Location:</span><span class="value">${contract.deliveryLocation || 'Yet to be confirmed'}</span></div>
        </div>

        <div class="section">
          <div class="section-title">Terms & Conditions</div>
          <p>1. The Seller agrees to provide quality ${contract.cropName} as per industry standards.</p>
          <p>2. The Buyer agrees to pay the advance amount within 7 days of contract execution.</p>
          <p>3. This contract is legally binding between ${contract.farmerName} and ${contract.buyerName}.</p>
          <p>Notes: ${contract.notes || 'None'}</p>
        </div>

        <div class="signatures">
          <div class="sig-box">Farmer's Signature</div>
          <div class="sig-box">Buyer's Signature</div>
        </div>

        <div class="footer">
          Generated by FarmConnect - Empowering Direct Trade
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    return uri;
  } catch (error) {
    console.error('PDF Generation Error:', error);
    return null;
  }
};