import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

export const generateContractPDF = async (contract) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Contract ${contract.id}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .title { color: #4CAF50; font-size: 24px; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; border-bottom: 1px solid #ccc; }
        .detail-row { margin-bottom: 8px; }
        .label { font-weight: bold; width: 150px; display: inline-block; }
        .signature { margin-top: 40px; }
        .signature-line { width: 200px; border-top: 1px solid #000; margin-top: 30px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">Agricultural Contract Agreement</h1>
        <p>Contract ID: ${contract.id}</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
      </div>
      
      <div class="section">
        <div class="section-title">Parties Involved</div>
        <div class="detail-row">
          <span class="label">Farmer:</span>
          <span>${contract.farmerName}</span>
        </div>
        <div class="detail-row">
          <span class="label">Buyer:</span>
          <span>${contract.buyerName}</span>
        </div>
      </div>
      
      <div class="section">
        <div class="section-title">Crop Details</div>
        <div class="detail-row">
          <span class="label">Crop Name:</span>
          <span>${contract.cropName}</span>
        </div>
        <div class="detail-row">
          <span class="label">Quantity:</span>
          <span>${contract.quantity} kg</span>
        </div>
        <div class="detail-row">
          <span class="label">Agreed Price:</span>
          <span>₹${contract.agreedPrice}/kg</span>
        </div>
        <div class="detail-row">
          <span class="label">Total Amount:</span>
          <span>₹${contract.totalAmount}</span>
        </div>
      </div>
      
      <div class="section">
        <div class="section-title">Payment Terms</div>
        <div class="detail-row">
          <span class="label">Advance (30%):</span>
          <span>₹${contract.advanceAmount}</span>
        </div>
        <div class="detail-row">
          <span class="label">Remaining (70%):</span>
          <span>₹${contract.remainingAmount}</span>
        </div>
      </div>
      
      <div class="section">
        <div class="section-title">Terms & Conditions</div>
        <p>1. 30% advance payment within 7 days of contract acceptance.</p>
        <p>2. Remaining 70% payment upon delivery of goods.</p>
        <p>3. Quality inspection allowed before acceptance.</p>
        <p>4. Contract cannot be cancelled after mutual agreement.</p>
      </div>
      
      <div class="signature">
        <div class="detail-row">
          <div class="signature-line" style="float: left;">
            <p>Farmer Signature</p>
          </div>
          <div class="signature-line" style="float: right;">
            <p>Buyer Signature</p>
          </div>
        </div>
      </div>
      
      <div class="footer">
        <p>This is a legally binding contract generated by Farmer Buyer Platform</p>
      </div>
    </body>
    </html>
  `;
  
  // Save HTML to file
  const htmlPath = `${FileSystem.documentDirectory}contract_${contract.id}.html`;
  await FileSystem.writeAsStringAsync(htmlPath, htmlContent);
  
  // For actual PDF generation, you would use a service like html2pdf
  // For now, return the HTML path
  return htmlPath;
};

export const downloadContractPDF = async (contract) => {
  const pdfPath = await generateContractPDF(contract);
  return pdfPath;
};

export const sharePDF = async (pdfPath) => {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(pdfPath);
    return true;
  }
  return false;
};

export const generateInvoicePDF = async (invoiceData) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Invoice</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; }
        .header { text-align: center; }
        .invoice-title { color: #4CAF50; font-size: 28px; }
        .invoice-details { margin: 20px 0; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="invoice-title">INVOICE</h1>
        <p>Invoice #: INV-${Date.now()}</p>
      </div>
      <!-- More invoice details -->
    </body>
    </html>
  `;
  
  const invoicePath = `${FileSystem.documentDirectory}invoice_${Date.now()}.html`;
  await FileSystem.writeAsStringAsync(invoicePath, htmlContent);
  return invoicePath;
};