import { colors } from './colors';
import { typography } from './typography';

export const lightTheme = {
  colors: {
    primary: colors.primary,
    primaryLight: colors.primaryLight,
    primaryDark: colors.primaryDark,
    secondary: colors.secondary,
    secondaryLight: colors.secondaryLight,
    secondaryDark: colors.secondaryDark,
    accent: colors.accent,
    accentLight: colors.accentLight,
    accentDark: colors.accentDark,
    success: colors.success,
    error: colors.error,
    warning: colors.warning,
    info: colors.info,
    background: colors.light.background,
    surface: colors.light.surface,
    card: colors.light.card,
    text: colors.light.text,
    textSecondary: colors.light.textSecondary,
    textHint: colors.light.textHint,
    border: colors.light.border,
    divider: colors.light.divider,
    disabled: colors.light.disabled,
    placeholder: colors.light.placeholder,
    icon: colors.light.icon,
    backdrop: colors.light.backdrop,
    status: colors.status,
  },
  typography,
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
    '5xl': 56,
  },
  borderRadius: {
    none: 0,
    sm: 4,
    md: 8,
    base: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    full: 9999,
  },
  elevation: {
    none: 0,
    sm: 2,
    md: 4,
    base: 6,
    lg: 8,
    xl: 10,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};

export const darkTheme = {
  colors: {
    primary: colors.primary,
    primaryLight: colors.primaryLight,
    primaryDark: colors.primaryDark,
    secondary: colors.secondary,
    secondaryLight: colors.secondaryLight,
    secondaryDark: colors.secondaryDark,
    accent: colors.accent,
    accentLight: colors.accentLight,
    accentDark: colors.accentDark,
    success: colors.success,
    error: colors.error,
    warning: colors.warning,
    info: colors.info,
    background: colors.dark.background,
    surface: colors.dark.surface,
    card: colors.dark.card,
    text: colors.dark.text,
    textSecondary: colors.dark.textSecondary,
    textHint: colors.dark.textHint,
    border: colors.dark.border,
    divider: colors.dark.divider,
    disabled: colors.dark.disabled,
    placeholder: colors.dark.placeholder,
    icon: colors.dark.icon,
    backdrop: colors.dark.backdrop,
    status: colors.status,
  },
  typography,
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    base: 16,
    lg: 20,
    xl: 24,
    '2xl': 32,
    '3xl': 40,
    '4xl': 48,
    '5xl': 56,
  },
  borderRadius: {
    none: 0,
    sm: 4,
    md: 8,
    base: 12,
    lg: 16,
    xl: 20,
    '2xl': 24,
    full: 9999,
  },
  elevation: {
    none: 0,
    sm: 2,
    md: 4,
    base: 6,
    lg: 8,
    xl: 10,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 2,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 8,
      elevation: 4,
    },
    xl: {
      shadowColor: '#000',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.6,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};

export const getTheme = (isDark = false) => {
  return isDark ? darkTheme : lightTheme;
};