import React, { createContext, useState, useEffect, useContext } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Localization from 'expo-localization';
import { useAuth } from './AuthContext';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    welcome: 'Welcome',
    login: 'Login',
    signup: 'Signup',
    logout: 'Logout',
    home: 'Home',
    profile: 'Profile',
    settings: 'Settings',
    crops: 'Crops',
    contracts: 'Contracts',
    payments: 'Payments',
    chat: 'Chat',
    notifications: 'Notifications',
    addCrop: 'Add Crop',
    negotiate: 'Negotiate',
    accept: 'Accept',
    reject: 'Reject',
    pending: 'Pending',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    total: 'Total',
    quantity: 'Quantity',
    price: 'Price',
    description: 'Description',
    location: 'Location',
    loading: 'Loading...',
    noData: 'No data found',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    share: 'Share',
    download: 'Download',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    about: 'About',
    version: 'Version',
    help: 'Help',
    support: 'Support',
    terms: 'Terms & Conditions',
    privacy: 'Privacy Policy',
    contact: 'Contact Us',
    earningsOverview: 'Earnings Overview',
    spendingAnalysis: 'Spending Analysis',
    quickActions: 'Quick Actions',
    topPicks: 'Top Picks For You',
    activeDeals: 'Active Deals',
    totalInvested: 'Total Invested',
    recentCrops: 'Recent Crops',
    searchPlaceholder: 'Search for fresh crops...',
    weatherForecast: 'Weather Forecast',
    seeAll: 'See All',
    market: 'Market',
    invested: 'Invested',
    earnings: 'Earnings',
    farmer: 'Farmer',
    buyer: 'Buyer',
    kgAvailable: 'kg available',
    monthJanShort: 'Jan',
    monthFebShort: 'Feb',
    monthMarShort: 'Mar',
    monthAprShort: 'Apr',
    monthMayShort: 'May',
    monthJunShort: 'Jun',
    actionRequired: 'Action Required',
    payAdvanceReminder: 'Please pay the 30% advance to finalize your contract for',
    payAdvanceNow: 'Pay Advance Now',
    newLabel: 'New',
    cropWheatShort: 'Wht',
    cropRiceShort: 'Rice',
    cropCornShort: 'Corn',
    cropSoyShort: 'Soy',
    cropTeaShort: 'Tea',
    pendingFarmerApproval: 'Pending Farmer Approval',
    created: 'Created',
    advancePaymentRequired: 'Advance Payment Required',
    advancePaid: 'Advance Paid',
    remaining: 'Remaining',
    dueOnDelivery: 'Due on delivery',
    downloadContractPdf: 'Download Contract PDF',
    contractPdfReady: 'Contract PDF is ready',
    share: 'Share',
    ok: 'OK',
    rejected: 'Rejected',
    acceptContract: 'Accept Contract',
    rejectContract: 'Reject Contract',
    acceptContractPrompt: 'Do you want to accept this contract? The buyer will be notified to pay the advance.',
    rejectContractPrompt: 'Are you sure you want to reject this contract?',
    contractAcceptedNotifyBuyer: 'Contract accepted! The buyer has been notified to pay the advance.',
    contractRejected: 'Contract rejected.',
    failedToUpdateContract: 'Failed to update contract',
    buyerPaymentPending: 'Buyer Payment Pending',
    advance: 'Advance',
    advanceReceivedPrepare: 'Advance Received! Prepare for delivery of',
    confirmPaymentReceived: 'Confirm Payment Received',
    confirmPaymentReceivedPrompt: 'Have you received this payment?',
    yes: 'Yes',
    no: 'No',
    paymentMarkedReceived: 'Payment marked as received',
    amount: 'Amount',
    type: 'Type',
    advancePaymentLabel: 'Advance Payment (30%)',
    remainingPaymentLabel: 'Remaining Payment (70%)',
    due: 'Due',
    paid: 'Paid',
    advanceReceivedNote: 'Advance payment received. Remaining 70% due on delivery.',
    markAsReceived: 'Mark as Received',
    totalEarned: 'Total Earned',
    received: 'Received',
    noPaymentRecords: 'No payment records found',
    payNow: 'Pay Now',
    paymentCompleted: 'Payment Completed',
    transactionId: 'TX ID',
    totalPaid: 'Total Paid',
    failedToLoadDetails: 'Failed to load details',
    loginToCreateContract: 'You must be logged in to create a contract.',
    enterDeliveryDate: 'Please enter delivery date in YYYY-MM-DD format',
    enterDeliveryLocation: 'Please enter delivery location',
    enterAdvanceAmount: 'Please enter advance amount',
    invalidAdvanceAmount: 'Invalid advance amount',
    contractCreated: 'Contract Created',
    contractSentForApproval: 'Your contract proposal has been sent to the farmer for approval.',
    viewContracts: 'View Contracts',
    failedToCreateContract: 'Failed to create contract: ',
    finalizeContract: 'Finalize Contract',
    agreedPrice: 'Agreed Price',
    totalAmount: 'Total Amount',
    deliveryAndPayment: 'Delivery & Payment',
    expectedDeliveryDate: 'Expected Delivery Date (YYYY-MM-DD)',
    dateFormatPlaceholder: 'YYYY-MM-DD',
    deliveryLocation: 'Delivery Location',
    enterDeliveryLocationPlaceholder: 'Enter delivery location',
    advancePaymentAuto: 'Advance Payment (30% Auto-calculated)',
    enterAmountToPayNow: 'Enter amount to pay now',
    additionalNotes: 'Additional Notes',
    deliveryInstructionsPlaceholder: 'Any specific delivery instructions...',
    sendContractProposal: 'Send Contract Proposal',
    acceptContractPromptShort: 'Do you want to accept this contract?',
    contractAccepted: 'Contract accepted successfully',
    contractRejectedMessage: 'The contract has been rejected',
    confirmDelivery: 'Confirm Delivery',
    confirmDeliveryPrompt: 'Mark delivery as completed and request remaining payment? This will notify the buyer to pay the balance.',
    deliveryMarkedComplete: 'Delivery marked complete. Remaining payment requested.',
    failedToUpdateDeliveryStatus: 'Failed to update delivery status',
    contract: 'Contract',
    contractDetails: 'Contract Details',
    parties: 'Parties',
    deliveryDetails: 'Delivery Details',
    deliveryDate: 'Delivery Date',
    notSet: 'Not set',
    toBeConfirmed: 'To be confirmed',
    deliveryStatus: 'Delivery Status',
    deliveredOn: 'Delivered On',
    termsAndConditions: 'Terms & Conditions',
    advancePaymentOf: 'Advance payment of',
    noAdvancePayment: 'No advance payment',
    requiredWithin7Days: 'required within 7 days.',
    remainingPaymentOf: 'Remaining payment of',
    dueUponDelivery: 'is due upon delivery.',
    qualityInspectionNote: 'Quality inspection can be done before final acceptance.',
    markDeliveryCompleteRequestBalance: 'Mark Delivery Complete & Request Balance',
    payAdvance: 'Pay Advance',
    all: 'All',
    noHistoryFound: 'No history found',
    deleteCrop: 'Delete Crop',
    deleteCropPrompt: 'Are you sure you want to delete this crop?',
    underContract: 'Under Contract',
    available: 'Available',
    noCropsAdded: 'No crops added yet',
    addFirstCrop: 'Add Your First Crop',
    fillRequiredFields: 'Please fill all required fields',
    cropAddedSuccessfully: 'Crop added successfully',
    cropNameRequired: 'Crop Name *',
    category: 'Category',
    category_vegetables: 'Vegetables',
    category_fruits: 'Fruits',
    category_grains: 'Grains',
    category_spices: 'Spices',
    category_others: 'Others',
    quantityRequiredKg: 'Quantity (in kg) *',
    pricePerKgRequired: 'Price per kg (₹) *',
    cropImages: 'Crop Images',
    gallery: 'Gallery',
    camera: 'Camera',
    cropUpdatedSuccessfully: 'Crop updated successfully',
    currentImages: 'Current Images',
    newImages: 'New Images',
    addMoreImages: 'Add More Images',
    updateCrop: 'Update Crop',
    shareCropPrefix: 'Check out this',
    shareMyCropPrefix: 'Check out my',
    shareCropAt: 'at',
    cropDetails: 'Crop Details',
    failedToShare: 'Failed to share',
    enterPriceQuantity: 'Please enter price and quantity',
    cropNotFound: 'Crop not found',
    quantityKg: 'Quantity (kg)',
    qualityGrade: 'Quality Grade',
    marketPriceComparison: 'Market Price Comparison',
    sellerPrice: 'Seller Price',
    marketAvg: 'Market Avg',
    youSave: 'You Save',
    noDescription: 'No description provided',
    locationNotSpecified: 'Location not specified',
    sellerInformation: 'Seller Information',
    reviews: 'reviews',
    india: 'India',
    chatWithFarmer: 'Chat with Farmer',
    makeContract: 'Make Contract',
    negotiatePrice: 'Negotiate Price',
    crop: 'Crop',
    offeredPricePlaceholder: 'Your offered price (₹/kg)',
    sendOffer: 'Send Offer',
    status: 'Status',
    notAvailable: 'Not Available',
    editCrop: 'Edit Crop',
    makeUnavailable: 'Make Unavailable',
    makeAvailable: 'Make Available',
    searchCrops: 'Search crops...',
    noCropsAvailable: 'No crops available',
    negotiationNotFound: 'Negotiation not found',
    newMessage: 'New Message',
    quantityCannotExceed: 'Quantity cannot exceed',
    newCounterOffer: 'New Counter Offer 🤝',
    offered: 'offered',
    for: 'for',
    acceptOffer: 'Accept Offer',
    acceptOfferPrompt: 'Accept',
    acceptOfferCreatesContract: 'This will create a contract proposal.',
    acceptCreateContract: 'Accept & Create Contract',
    acceptBuyerOffer: 'Accept Buyer Offer',
    contractCreatedImmediately: 'A contract will be created immediately.',
    contractCreatedCelebration: 'Contract Created! 🎉',
    contractActiveAdvanceNotify: 'The contract is now active. The buyer has been notified to pay the advance.',
    contractCreatedNegotiationLocked: 'Contract created — negotiation locked',
    noMessagesYet: 'No messages yet.',
    sendOfferToStart: 'Send an offer to start negotiating.',
    sendCounterOffer: 'Send Counter Offer',
    pricePerKgPlaceholder: '₹ Price/kg',
    quantityKgPlaceholder: 'Qty (kg)',
    send: 'Send',
    typeMessage: 'Type a message...',
    couldNotLoadPaymentDetails: 'Could not load payment details: ',
    goBack: 'Go Back',
    paymentFailed: 'Payment Failed',
    razorpayKeyNotConfigured: 'Razorpay key is not configured.',
    invalidPaymentAmount: 'Invalid payment amount.',
    paymentVerificationFailed: 'Payment verification failed.',
    paymentSuccessful: 'Payment Successful',
    paidSuccessfully: 'paid successfully',
    paymentDetails: 'Payment Details',
    contractId: 'Contract ID',
    paymentType: 'Payment Type',
    amountToPay: 'Amount to Pay',
    paymentMethods: 'Payment Methods',
    creditDebitCard: 'Credit/Debit Card',
    payUsingCard: 'Pay using card',
    upi: 'UPI',
    googlePayPhonePePaytm: 'Google Pay, PhonePe, Paytm',
    netBanking: 'Net Banking',
    allMajorBanks: 'All major banks',
    payWithRazorpay: 'Pay with Razorpay',
    simulatePayment: 'Simulate Payment',
    deleteNotification: 'Delete Notification',
    confirmDelete: 'Are you sure?',
    noNotifications: 'No notifications',
    allCaughtUp: "You're all caught up!",
    startConversation: 'Start a conversation!',
    languageChanged: 'Language Changed',
    appLanguageChangedTo: 'App language changed to',
    clearCache: 'Clear Cache',
    clearCachePrompt: 'Are you sure you want to clear app cache?',
    clear: 'Clear',
    cacheCleared: 'Cache cleared successfully',
    pushNotifications: 'Push Notifications',
    sound: 'Sound',
    reportIssue: 'Report an Issue',
    appName: 'Farmer Buyer Contract',
    allRightsReserved: '© 2024 All rights reserved',
    success: 'Success',
    error: 'Error',
    history: 'History',
    farmName: 'Farm Name',
    farmSize: 'Farm Size',
    notProvided: 'Not provided',
    sendMessage: 'Send Message',
    aboutFarmer: 'About Farmer',
    defaultFarmerBio: 'Experienced farmer dedicated to providing high-quality organic produce.',
    totalSales: 'Total Sales',
    cropsListed: 'Crops Listed',
    customerReviews: 'Customer Reviews',
    noReviews: 'No reviews yet',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter your phone number',
    enterLocation: 'Enter your location',
    bio: 'Bio',
    enterBio: 'Tell us about yourself',
    enterFarmName: 'Enter your farm name',
    enterFarmSize: 'e.g., 5 acres',
    saveChanges: 'Save Changes',
    nameRequired: 'Name is required',
    profileUpdated: 'Profile updated successfully'
  },
  hi: {
    welcome: 'स्वागत है',
    login: 'लॉगिन',
    signup: 'साइनअप',
    logout: 'लॉगआउट',
    home: 'होम',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    crops: 'फसलें',
    contracts: 'अनुबंध',
    payments: 'भुगतान',
    chat: 'चैट',
    notifications: 'सूचनाएं',
    addCrop: 'फसल जोड़ें',
    negotiate: 'मोलभाव करें',
    accept: 'स्वीकार करें',
    reject: 'अस्वीकार करें',
    pending: 'लंबित',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    cancelled: 'रद्द',
    total: 'कुल',
    quantity: 'मात्रा',
    price: 'कीमत',
    description: 'विवरण',
    location: 'स्थान',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा नहीं मिला',
    retry: 'पुनः प्रयास करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    share: 'साझा करें',
    download: 'डाउनलोड',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    sort: 'क्रमबद्ध करें',
    language: 'भाषा',
    theme: 'थीम',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    about: 'हमारे बारे में',
    version: 'संस्करण',
    help: 'सहायता',
    support: 'समर्थन',
    terms: 'नियम और शर्तें',
    privacy: 'गोपनीयता नीति',
    contact: 'संपर्क करें',
    earningsOverview: 'कमाई का अवलोकन',
    spendingAnalysis: 'खर्च का विश्लेषण',
    quickActions: 'त्वरित कार्रवाई',
    topPicks: 'आपके लिए बेहतरीन विकल्प',
    activeDeals: 'सक्रिय सौदे',
    totalInvested: 'कुल निवेश',
    recentCrops: 'हाल की फसलें',
    searchPlaceholder: 'ताजी फसलों की खोज करें...',
    weatherForecast: 'मौसम का पूर्वानुमान',
    seeAll: 'सभी देखें',
    market: 'बाज़ार',
    invested: 'निवेशित',
    earnings: 'कमाई',
    farmer: 'किसान',
    buyer: 'खरीदार',
    kgAvailable: 'किलो उपलब्ध',
    monthJanShort: 'जन',
    monthFebShort: 'फर',
    monthMarShort: 'मार्च',
    monthAprShort: 'अप्र',
    monthMayShort: 'मई',
    monthJunShort: 'जून',
    actionRequired: 'कार्रवाई आवश्यक',
    payAdvanceReminder: 'कृपया 30% अग्रिम भुगतान करें ताकि आपका अनुबंध पूरा हो सके',
    payAdvanceNow: 'अभी अग्रिम भुगतान करें',
    newLabel: 'नया',
    cropWheatShort: 'गेहूं',
    cropRiceShort: 'चावल',
    cropCornShort: 'मक्का',
    cropSoyShort: 'सोय',
    cropTeaShort: 'चाय',
    pendingFarmerApproval: 'किसान की स्वीकृति लंबित',
    created: 'बनाया गया',
    advancePaymentRequired: 'अग्रिम भुगतान आवश्यक',
    advancePaid: 'अग्रिम भुगतान किया',
    remaining: 'शेष',
    dueOnDelivery: 'डिलीवरी पर देय',
    downloadContractPdf: 'अनुबंध PDF डाउनलोड करें',
    contractPdfReady: 'अनुबंध PDF तैयार है',
    share: 'शेयर करें',
    ok: 'ठीक है',
    rejected: 'अस्वीकृत',
    acceptContract: 'अनुबंध स्वीकार करें',
    rejectContract: 'अनुबंध अस्वीकार करें',
    acceptContractPrompt: 'क्या आप इस अनुबंध को स्वीकार करना चाहते हैं? खरीदार को अग्रिम भुगतान के लिए सूचित किया जाएगा।',
    rejectContractPrompt: 'क्या आप वाकई इस अनुबंध को अस्वीकार करना चाहते हैं?',
    contractAcceptedNotifyBuyer: 'अनुबंध स्वीकार हुआ! खरीदार को अग्रिम भुगतान के लिए सूचित किया गया है।',
    contractRejected: 'अनुबंध अस्वीकार हुआ।',
    failedToUpdateContract: 'अनुबंध अपडेट करने में विफल',
    buyerPaymentPending: 'खरीदार भुगतान लंबित',
    advance: 'अग्रिम',
    advanceReceivedPrepare: 'अग्रिम प्राप्त हुआ! डिलीवरी की तैयारी करें',
    confirmPaymentReceived: 'भुगतान प्राप्ति की पुष्टि',
    confirmPaymentReceivedPrompt: 'क्या आपको यह भुगतान प्राप्त हुआ है?',
    yes: 'हाँ',
    no: 'नहीं',
    paymentMarkedReceived: 'भुगतान प्राप्त के रूप में चिह्नित',
    amount: 'राशि',
    type: 'प्रकार',
    advancePaymentLabel: 'अग्रिम भुगतान (30%)',
    remainingPaymentLabel: 'शेष भुगतान (70%)',
    due: 'देय',
    paid: 'भुगतान',
    advanceReceivedNote: 'अग्रिम भुगतान प्राप्त हुआ। शेष 70% डिलीवरी पर देय है।',
    markAsReceived: 'प्राप्त के रूप में चिह्नित करें',
    totalEarned: 'कुल कमाई',
    received: 'प्राप्त',
    noPaymentRecords: 'कोई भुगतान रिकॉर्ड नहीं मिला',
    payNow: 'अभी भुगतान करें',
    paymentCompleted: 'भुगतान पूरा',
    transactionId: 'लेन-देन आईडी',
    totalPaid: 'कुल भुगतान',
    failedToLoadDetails: 'विवरण लोड करने में विफल',
    loginToCreateContract: 'अनुबंध बनाने के लिए लॉगिन करें।',
    enterDeliveryDate: 'कृपया डिलीवरी तारीख YYYY-MM-DD में दर्ज करें',
    enterDeliveryLocation: 'कृपया डिलीवरी स्थान दर्ज करें',
    enterAdvanceAmount: 'कृपया अग्रिम राशि दर्ज करें',
    invalidAdvanceAmount: 'अमान्य अग्रिम राशि',
    contractCreated: 'अनुबंध बनाया गया',
    contractSentForApproval: 'आपका अनुबंध प्रस्ताव किसान को स्वीकृति के लिए भेजा गया है।',
    viewContracts: 'अनुबंध देखें',
    failedToCreateContract: 'अनुबंध बनाने में विफल: ',
    finalizeContract: 'अनुबंध अंतिम करें',
    agreedPrice: 'तय कीमत',
    totalAmount: 'कुल राशि',
    deliveryAndPayment: 'डिलीवरी और भुगतान',
    expectedDeliveryDate: 'अपेक्षित डिलीवरी तारीख (YYYY-MM-DD)',
    dateFormatPlaceholder: 'YYYY-MM-DD',
    deliveryLocation: 'डिलीवरी स्थान',
    enterDeliveryLocationPlaceholder: 'डिलीवरी स्थान दर्ज करें',
    advancePaymentAuto: 'अग्रिम भुगतान (30% स्वतः)',
    enterAmountToPayNow: 'अभी भुगतान करने की राशि दर्ज करें',
    additionalNotes: 'अतिरिक्त नोट्स',
    deliveryInstructionsPlaceholder: 'डिलीवरी निर्देश...',
    sendContractProposal: 'अनुबंध प्रस्ताव भेजें',
    acceptContractPromptShort: 'क्या आप इस अनुबंध को स्वीकार करना चाहते हैं?',
    contractAccepted: 'अनुबंध सफलतापूर्वक स्वीकार हुआ',
    contractRejectedMessage: 'अनुबंध अस्वीकार किया गया',
    confirmDelivery: 'डिलीवरी की पुष्टि',
    confirmDeliveryPrompt: 'डिलीवरी पूर्ण चिह्नित करें और शेष भुगतान अनुरोध करें? खरीदार को सूचित किया जाएगा।',
    deliveryMarkedComplete: 'डिलीवरी पूर्ण चिह्नित। शेष भुगतान का अनुरोध किया गया।',
    failedToUpdateDeliveryStatus: 'डिलीवरी स्थिति अपडेट करने में विफल',
    contract: 'अनुबंध',
    contractDetails: 'अनुबंध विवरण',
    parties: 'पक्ष',
    deliveryDetails: 'डिलीवरी विवरण',
    deliveryDate: 'डिलीवरी तारीख',
    notSet: 'सेट नहीं',
    toBeConfirmed: 'पुष्टि बाकी',
    deliveryStatus: 'डिलीवरी स्थिति',
    deliveredOn: 'डिलीवर किया गया',
    termsAndConditions: 'नियम और शर्तें',
    advancePaymentOf: 'अग्रिम भुगतान',
    noAdvancePayment: 'कोई अग्रिम भुगतान नहीं',
    requiredWithin7Days: '7 दिनों के भीतर आवश्यक।',
    remainingPaymentOf: 'शेष भुगतान',
    dueUponDelivery: 'डिलीवरी पर देय है।',
    qualityInspectionNote: 'अंतिम स्वीकृति से पहले गुणवत्ता जांच की जा सकती है।',
    markDeliveryCompleteRequestBalance: 'डिलीवरी पूर्ण चिह्नित करें और शेष भुगतान अनुरोध करें',
    payAdvance: 'अग्रिम भुगतान करें',
    all: 'सभी',
    noHistoryFound: 'कोई इतिहास नहीं मिला',
    deleteCrop: 'फसल हटाएं',
    deleteCropPrompt: 'क्या आप वाकई इस फसल को हटाना चाहते हैं?',
    underContract: 'अनुबंध में',
    available: 'उपलब्ध',
    noCropsAdded: 'अभी तक कोई फसल नहीं जोड़ी गई',
    addFirstCrop: 'पहली फसल जोड़ें',
    fillRequiredFields: 'कृपया सभी आवश्यक फ़ील्ड भरें',
    cropAddedSuccessfully: 'फसल सफलतापूर्वक जोड़ी गई',
    cropNameRequired: 'फसल का नाम *',
    category: 'श्रेणी',
    category_vegetables: 'सब्ज़ियाँ',
    category_fruits: 'फल',
    category_grains: 'अनाज',
    category_spices: 'मसाले',
    category_others: 'अन्य',
    quantityRequiredKg: 'मात्रा (किलो में) *',
    pricePerKgRequired: 'प्रति किलो मूल्य (₹) *',
    cropImages: 'फसल की तस्वीरें',
    gallery: 'गैलरी',
    camera: 'कैमरा',
    cropUpdatedSuccessfully: 'फसल सफलतापूर्वक अपडेट हुई',
    currentImages: 'वर्तमान तस्वीरें',
    newImages: 'नई तस्वीरें',
    addMoreImages: 'और तस्वीरें जोड़ें',
    updateCrop: 'फसल अपडेट करें',
    shareCropPrefix: 'इस फसल को देखें',
    shareMyCropPrefix: 'मेरी फसल देखें',
    shareCropAt: 'की कीमत',
    cropDetails: 'फसल विवरण',
    failedToShare: 'शेयर करने में विफल',
    enterPriceQuantity: 'कृपया कीमत और मात्रा दर्ज करें',
    cropNotFound: 'फसल नहीं मिली',
    quantityKg: 'मात्रा (किलो)',
    qualityGrade: 'गुणवत्ता ग्रेड',
    marketPriceComparison: 'बाजार मूल्य तुलना',
    sellerPrice: 'विक्रेता मूल्य',
    marketAvg: 'बाजार औसत',
    youSave: 'आप बचाते हैं',
    noDescription: 'कोई विवरण नहीं',
    locationNotSpecified: 'स्थान निर्दिष्ट नहीं',
    sellerInformation: 'विक्रेता जानकारी',
    reviews: 'समीक्षाएँ',
    india: 'भारत',
    chatWithFarmer: 'किसान से चैट करें',
    makeContract: 'अनुबंध बनाएं',
    negotiatePrice: 'कीमत पर बातचीत',
    crop: 'फसल',
    offeredPricePlaceholder: 'आपकी पेशकश (₹/किलो)',
    sendOffer: 'प्रस्ताव भेजें',
    status: 'स्थिति',
    notAvailable: 'उपलब्ध नहीं',
    editCrop: 'फसल संपादित करें',
    makeUnavailable: 'अनुपलब्ध करें',
    makeAvailable: 'उपलब्ध करें',
    searchCrops: 'फसल खोजें...',
    noCropsAvailable: 'कोई फसल उपलब्ध नहीं',
    negotiationNotFound: 'बातचीत नहीं मिली',
    newMessage: 'नया संदेश',
    quantityCannotExceed: 'मात्रा इससे अधिक नहीं हो सकती',
    newCounterOffer: 'नया काउंटर ऑफर 🤝',
    offered: 'ने ऑफर किया',
    for: 'के लिए',
    acceptOffer: 'ऑफर स्वीकार करें',
    acceptOfferPrompt: 'स्वीकार करें',
    acceptOfferCreatesContract: 'यह अनुबंध प्रस्ताव बनाएगा।',
    acceptCreateContract: 'स्वीकार करें और अनुबंध बनाएं',
    acceptBuyerOffer: 'खरीदार का ऑफर स्वीकार करें',
    contractCreatedImmediately: 'अनुबंध तुरंत बनाया जाएगा।',
    contractCreatedCelebration: 'अनुबंध बन गया! 🎉',
    contractActiveAdvanceNotify: 'अनुबंध सक्रिय है। खरीदार को अग्रिम भुगतान के लिए सूचित किया गया है।',
    contractCreatedNegotiationLocked: 'अनुबंध बना — बातचीत लॉक है',
    noMessagesYet: 'अभी कोई संदेश नहीं।',
    sendOfferToStart: 'बातचीत शुरू करने के लिए ऑफर भेजें।',
    sendCounterOffer: 'काउंटर ऑफर भेजें',
    pricePerKgPlaceholder: '₹ प्रति किलो',
    quantityKgPlaceholder: 'मात्रा (किलो)',
    send: 'भेजें',
    typeMessage: 'संदेश लिखें...',
    couldNotLoadPaymentDetails: 'भुगतान विवरण लोड नहीं हो सके: ',
    goBack: 'वापस जाएं',
    paymentFailed: 'भुगतान विफल',
    razorpayKeyNotConfigured: 'Razorpay कुंजी कॉन्फ़िगर नहीं है।',
    invalidPaymentAmount: 'अमान्य भुगतान राशि।',
    paymentVerificationFailed: 'भुगतान सत्यापन विफल।',
    paymentSuccessful: 'भुगतान सफल',
    paidSuccessfully: 'सफलतापूर्वक भुगतान हुआ',
    paymentDetails: 'भुगतान विवरण',
    contractId: 'अनुबंध आईडी',
    paymentType: 'भुगतान प्रकार',
    amountToPay: 'भुगतान की राशि',
    paymentMethods: 'भुगतान के तरीके',
    creditDebitCard: 'क्रेडिट/डेबिट कार्ड',
    payUsingCard: 'कार्ड से भुगतान करें',
    upi: 'UPI',
    googlePayPhonePePaytm: 'Google Pay, PhonePe, Paytm',
    netBanking: 'नेट बैंकिंग',
    allMajorBanks: 'सभी प्रमुख बैंक',
    payWithRazorpay: 'Razorpay से भुगतान करें',
    simulatePayment: 'भुगतान सिमुलेट करें',
    deleteNotification: 'सूचना हटाएं',
    confirmDelete: 'क्या आप सुनिश्चित हैं?',
    noNotifications: 'कोई सूचनाएँ नहीं',
    allCaughtUp: 'आप सबकुछ देख चुके हैं!',
    startConversation: 'बातचीत शुरू करें!',
    languageChanged: 'भाषा बदली गई',
    appLanguageChangedTo: 'ऐप भाषा बदली गई',
    clearCache: 'कैश साफ़ करें',
    clearCachePrompt: 'क्या आप ऐप कैश साफ़ करना चाहते हैं?',
    clear: 'साफ़ करें',
    cacheCleared: 'कैश सफलतापूर्वक साफ़ हुआ',
    pushNotifications: 'पुश सूचनाएँ',
    sound: 'ध्वनि',
    reportIssue: 'समस्या रिपोर्ट करें',
    appName: 'Farmer Buyer Contract',
    allRightsReserved: '© 2024 सर्वाधिकार सुरक्षित',
    success: 'सफल',
    error: 'त्रुटि',
    history: 'इतिहास',
    farmName: 'फार्म का नाम',
    farmSize: 'फार्म का आकार',
    notProvided: 'प्रदान नहीं',
    sendMessage: 'संदेश भेजें',
    aboutFarmer: 'किसान के बारे में',
    defaultFarmerBio: 'अनुभवी किसान जो उच्च गुणवत्ता की जैविक उपज प्रदान करते हैं।',
    totalSales: 'कुल बिक्री',
    cropsListed: 'सूचीबद्ध फसलें',
    customerReviews: 'ग्राहक समीक्षाएँ',
    noReviews: 'अभी कोई समीक्षा नहीं',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    phoneNumber: 'फ़ोन नंबर',
    enterPhoneNumber: 'अपना फ़ोन नंबर दर्ज करें',
    enterLocation: 'अपना स्थान दर्ज करें',
    bio: 'परिचय',
    enterBio: 'अपने बारे में बताएं',
    enterFarmName: 'अपने फार्म का नाम दर्ज करें',
    enterFarmSize: 'जैसे, 5 एकड़',
    saveChanges: 'परिवर्तन सहेजें',
    nameRequired: 'नाम आवश्यक है',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई'
  },
  mr: {
    welcome: 'स्वागत आहे',
    login: 'लॉगिन',
    signup: 'साइनअप',
    logout: 'लॉगआउट',
    home: 'मुख्यपृष्ठ',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्ज',
    crops: 'पिके',
    contracts: 'करार',
    payments: 'देयके',
    chat: 'गप्पा',
    notifications: 'सूचना',
    addCrop: 'पीक जोडा',
    negotiate: 'भाव करा',
    accept: 'स्वीकारा',
    reject: 'नकारा',
    pending: 'प्रलंबित',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    cancelled: 'रद्द',
    total: 'एकूण',
    quantity: 'प्रमाण',
    price: 'किंमत',
    description: 'वर्णन',
    location: 'स्थान',
    loading: 'लोड होत आहे...',
    noData: 'वेळापत्रक सापडले नाही',
    retry: 'पुन्हा प्रयत्न करा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    share: 'शेअर करा',
    download: 'डाउनलोड',
    search: 'शोधा',
    filter: 'फिल्टर',
    sort: 'क्रमवारी',
    language: 'भाषा',
    theme: 'थीम',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    about: 'आमच्याबद्दल',
    version: 'आवृत्ती',
    help: 'मदत',
    support: 'सहाय्य',
    terms: 'अटी आणि नियम',
    privacy: 'गोपनीयता धोरण',
    contact: 'संपर्क',
    earningsOverview: 'उत्पन्नाचे विहंगावलोकन',
    spendingAnalysis: 'खर्चाचे विश्लेषण',
    quickActions: 'त्वरित कृती',
    topPicks: 'तुमच्यासाठी सर्वोत्तम निवडी',
    activeDeals: 'सक्रिय सौदे',
    totalInvested: 'एकूण गुंतवणूक',
    recentCrops: 'अलीकडील पिके',
    searchPlaceholder: 'ताज्या पिकांचा शोध घ्या...',
    weatherForecast: 'हवामान अंदाज',
    seeAll: 'सर्व पहा',
    market: 'बाजार',
    invested: 'गुंतवणूक',
    earnings: 'उत्पन्न',
    farmer: 'शेतकरी',
    buyer: 'खरेदीदार',
    kgAvailable: 'किलो उपलब्ध',
    monthJanShort: 'जाने',
    monthFebShort: 'फेब',
    monthMarShort: 'मार्च',
    monthAprShort: 'एप्र',
    monthMayShort: 'मे',
    monthJunShort: 'जून',
    actionRequired: 'कारवाई आवश्यक',
    payAdvanceReminder: 'कृपया 30% आगाऊ भरणा करून करार पूर्ण करा',
    payAdvanceNow: 'आत्ताच आगाऊ भरा',
    newLabel: 'नवीन',
    cropWheatShort: 'गहू',
    cropRiceShort: 'तांदूळ',
    cropCornShort: 'मका',
    cropSoyShort: 'सोया',
    cropTeaShort: 'चहा',
    pendingFarmerApproval: 'शेतकरी मंजुरी प्रलंबित',
    created: 'तयार केले',
    advancePaymentRequired: 'आगाऊ भरणा आवश्यक',
    advancePaid: 'आगाऊ भरले',
    remaining: 'उरलेले',
    dueOnDelivery: 'डिलिव्हरीवेळी देय',
    downloadContractPdf: 'करार PDF डाउनलोड करा',
    contractPdfReady: 'करार PDF तयार आहे',
    share: 'शेअर करा',
    ok: 'ठीक आहे',
    rejected: 'नाकारले',
    acceptContract: 'करार स्वीकारा',
    rejectContract: 'करार नाकारा',
    acceptContractPrompt: 'हा करार स्वीकारायचा का? खरेदीदाराला आगाऊ भरण्यासाठी सूचित केले जाईल.',
    rejectContractPrompt: 'हा करार नाकारायचा का?',
    contractAcceptedNotifyBuyer: 'करार स्वीकारला! खरेदीदाराला आगाऊ भरण्यासाठी सूचित केले.',
    contractRejected: 'करार नाकारला.',
    failedToUpdateContract: 'करार अपडेट करण्यात अयशस्वी',
    buyerPaymentPending: 'खरेदीदाराचे पेमेंट प्रलंबित',
    advance: 'आगाऊ',
    advanceReceivedPrepare: 'आगाऊ मिळाले! डिलिव्हरीची तयारी करा',
    confirmPaymentReceived: 'पेमेंट प्राप्तीची पुष्टी',
    confirmPaymentReceivedPrompt: 'हे पेमेंट मिळाले का?',
    yes: 'होय',
    no: 'नाही',
    paymentMarkedReceived: 'पेमेंट प्राप्त म्हणून चिन्हांकित',
    amount: 'रक्कम',
    type: 'प्रकार',
    advancePaymentLabel: 'आगाऊ पेमेंट (30%)',
    remainingPaymentLabel: 'शिल्लक पेमेंट (70%)',
    due: 'देय',
    paid: 'भरले',
    advanceReceivedNote: 'आगाऊ पेमेंट मिळाले. उर्वरित 70% डिलिव्हरीवेळी देय.',
    markAsReceived: 'प्राप्त म्हणून चिन्हांकित करा',
    totalEarned: 'एकूण कमाई',
    received: 'प्राप्त',
    noPaymentRecords: 'पेमेंट रेकॉर्ड सापडले नाही',
    payNow: 'आता भरा',
    paymentCompleted: 'पेमेंट पूर्ण',
    transactionId: 'व्यवहार आयडी',
    totalPaid: 'एकूण पेमेंट',
    failedToLoadDetails: 'तपशील लोड करण्यात अयशस्वी',
    loginToCreateContract: 'करार तयार करण्यासाठी लॉगिन करा.',
    enterDeliveryDate: 'कृपया डिलिव्हरी तारीख YYYY-MM-DD मध्ये टाका',
    enterDeliveryLocation: 'कृपया डिलिव्हरी ठिकाण टाका',
    enterAdvanceAmount: 'कृपया आगाऊ रक्कम टाका',
    invalidAdvanceAmount: 'अवैध आगाऊ रक्कम',
    contractCreated: 'करार तयार झाला',
    contractSentForApproval: 'तुमचा करार प्रस्ताव शेतकऱ्याकडे मंजुरीसाठी पाठवला आहे.',
    viewContracts: 'करार पाहा',
    failedToCreateContract: 'करार तयार करण्यात अयशस्वी: ',
    finalizeContract: 'करार अंतिम करा',
    agreedPrice: 'तय किंमत',
    totalAmount: 'एकूण रक्कम',
    deliveryAndPayment: 'डिलिव्हरी आणि पेमेंट',
    expectedDeliveryDate: 'अपेक्षित डिलिव्हरी तारीख (YYYY-MM-DD)',
    dateFormatPlaceholder: 'YYYY-MM-DD',
    deliveryLocation: 'डिलिव्हरी ठिकाण',
    enterDeliveryLocationPlaceholder: 'डिलिव्हरी ठिकाण टाका',
    advancePaymentAuto: 'आगाऊ पेमेंट (30% स्वयं)',
    enterAmountToPayNow: 'आत्ताच्या पेमेंटची रक्कम टाका',
    additionalNotes: 'अतिरिक्त नोंदी',
    deliveryInstructionsPlaceholder: 'डिलिव्हरी सूचना...',
    sendContractProposal: 'करार प्रस्ताव पाठवा',
    acceptContractPromptShort: 'हा करार स्वीकारायचा का?',
    contractAccepted: 'करार यशस्वीरित्या स्वीकारला',
    contractRejectedMessage: 'करार नाकारला',
    confirmDelivery: 'डिलिव्हरीची पुष्टी',
    confirmDeliveryPrompt: 'डिलिव्हरी पूर्ण म्हणून चिन्हांकित करून उर्वरित पेमेंट मागवायचे? खरेदीदाराला सूचित केले जाईल.',
    deliveryMarkedComplete: 'डिलिव्हरी पूर्ण. उर्वरित पेमेंटची मागणी केली.',
    failedToUpdateDeliveryStatus: 'डिलिव्हरी स्थिती अपडेट करण्यात अयशस्वी',
    contract: 'करार',
    contractDetails: 'करार तपशील',
    parties: 'पक्ष',
    deliveryDetails: 'डिलिव्हरी तपशील',
    deliveryDate: 'डिलिव्हरी तारीख',
    notSet: 'सेट नाही',
    toBeConfirmed: 'पुष्टी बाकी',
    deliveryStatus: 'डिलिव्हरी स्थिती',
    deliveredOn: 'डिलिव्हरी दिनांक',
    termsAndConditions: 'अटी व शर्ती',
    advancePaymentOf: 'आगाऊ पेमेंट',
    noAdvancePayment: 'आगाऊ पेमेंट नाही',
    requiredWithin7Days: '7 दिवसांत आवश्यक.',
    remainingPaymentOf: 'शिल्लक पेमेंट',
    dueUponDelivery: 'डिलिव्हरीवेळी देय.',
    qualityInspectionNote: 'अंतिम स्वीकृतीपूर्वी गुणवत्ता तपासणी करता येते.',
    markDeliveryCompleteRequestBalance: 'डिलिव्हरी पूर्ण चिन्हांकित करून शिल्लक मागवा',
    payAdvance: 'आगाऊ भरा',
    all: 'सर्व',
    noHistoryFound: 'इतिहास सापडला नाही',
    deleteCrop: 'पीक हटवा',
    deleteCropPrompt: 'हे पीक हटवायचे का?',
    underContract: 'करारात',
    available: 'उपलब्ध',
    noCropsAdded: 'अजून कोणतेही पीक जोडले नाही',
    addFirstCrop: 'पहिले पीक जोडा',
    fillRequiredFields: 'कृपया सर्व आवश्यक फील्ड भरा',
    cropAddedSuccessfully: 'पीक यशस्वीरित्या जोडले',
    cropNameRequired: 'पीक नाव *',
    category: 'वर्ग',
    category_vegetables: 'भाज्या',
    category_fruits: 'फळे',
    category_grains: 'धान्य',
    category_spices: 'मसाले',
    category_others: 'इतर',
    quantityRequiredKg: 'मात्रा (किलो) *',
    pricePerKgRequired: 'प्रति किलो किंमत (₹) *',
    cropImages: 'पीक प्रतिमा',
    gallery: 'गॅलरी',
    camera: 'कॅमेरा',
    cropUpdatedSuccessfully: 'पीक यशस्वीरित्या अपडेट झाले',
    currentImages: 'सध्याच्या प्रतिमा',
    newImages: 'नवीन प्रतिमा',
    addMoreImages: 'अधिक प्रतिमा जोडा',
    updateCrop: 'पीक अपडेट करा',
    shareCropPrefix: 'हे पीक पहा',
    shareMyCropPrefix: 'माझे पीक पहा',
    shareCropAt: 'दराने',
    cropDetails: 'पीक तपशील',
    failedToShare: 'शेअर करण्यात अयशस्वी',
    enterPriceQuantity: 'कृपया किंमत आणि मात्रा टाका',
    cropNotFound: 'पीक सापडले नाही',
    quantityKg: 'मात्रा (किलो)',
    qualityGrade: 'गुणवत्ता ग्रेड',
    marketPriceComparison: 'बाजार दर तुलना',
    sellerPrice: 'विक्रेता दर',
    marketAvg: 'बाजार सरासरी',
    youSave: 'तुम्ही बचत करता',
    noDescription: 'वर्णन उपलब्ध नाही',
    locationNotSpecified: 'स्थान दिलेले नाही',
    sellerInformation: 'विक्रेता माहिती',
    reviews: 'पुनरावलोकने',
    india: 'भारत',
    chatWithFarmer: 'शेतकऱ्याशी चॅट करा',
    makeContract: 'करार तयार करा',
    negotiatePrice: 'किंमत बोलणी',
    crop: 'पीक',
    offeredPricePlaceholder: 'तुमची ऑफर (₹/किलो)',
    sendOffer: 'ऑफर पाठवा',
    status: 'स्थिती',
    notAvailable: 'उपलब्ध नाही',
    editCrop: 'पीक संपादित करा',
    makeUnavailable: 'अनुपलब्ध करा',
    makeAvailable: 'उपलब्ध करा',
    searchCrops: 'पीके शोधा...',
    noCropsAvailable: 'कोणतेही पीक उपलब्ध नाही',
    negotiationNotFound: 'बोलणी सापडली नाही',
    newMessage: 'नवा संदेश',
    quantityCannotExceed: 'मात्रा यापेक्षा जास्त असू शकत नाही',
    newCounterOffer: 'नवीन काउंटर ऑफर 🤝',
    offered: 'ऑफर केली',
    for: 'साठी',
    acceptOffer: 'ऑफर स्वीकारा',
    acceptOfferPrompt: 'स्वीकारा',
    acceptOfferCreatesContract: 'यामुळे करार प्रस्ताव तयार होईल.',
    acceptCreateContract: 'स्वीकारून करार करा',
    acceptBuyerOffer: 'खरेदीदाराची ऑफर स्वीकारा',
    contractCreatedImmediately: 'करार त्वरित तयार होईल.',
    contractCreatedCelebration: 'करार तयार झाला! 🎉',
    contractActiveAdvanceNotify: 'करार सक्रिय आहे. खरेदीदाराला आगाऊ भरण्यासाठी सूचित केले आहे.',
    contractCreatedNegotiationLocked: 'करार तयार — बोलणी लॉक',
    noMessagesYet: 'अजून संदेश नाही.',
    sendOfferToStart: 'बोलणी सुरू करण्यासाठी ऑफर पाठवा.',
    sendCounterOffer: 'काउंटर ऑफर पाठवा',
    pricePerKgPlaceholder: '₹ प्रति किलो',
    quantityKgPlaceholder: 'मात्रा (किलो)',
    send: 'पाठवा',
    typeMessage: 'संदेश लिहा...',
    couldNotLoadPaymentDetails: 'पेमेंट तपशील लोड होऊ शकले नाही: ',
    goBack: 'मागे जा',
    paymentFailed: 'पेमेंट अयशस्वी',
    razorpayKeyNotConfigured: 'Razorpay की सेट केलेली नाही.',
    invalidPaymentAmount: 'अवैध पेमेंट रक्कम.',
    paymentVerificationFailed: 'पेमेंट पडताळणी अयशस्वी.',
    paymentSuccessful: 'पेमेंट यशस्वी',
    paidSuccessfully: 'यशस्वीरित्या भरले',
    paymentDetails: 'पेमेंट तपशील',
    contractId: 'करार आयडी',
    paymentType: 'पेमेंट प्रकार',
    amountToPay: 'देय रक्कम',
    paymentMethods: 'पेमेंट पद्धती',
    creditDebitCard: 'क्रेडिट/डेबिट कार्ड',
    payUsingCard: 'कार्डने पेमेंट करा',
    upi: 'UPI',
    googlePayPhonePePaytm: 'Google Pay, PhonePe, Paytm',
    netBanking: 'नेट बँकिंग',
    allMajorBanks: 'सर्व प्रमुख बँका',
    payWithRazorpay: 'Razorpay ने पेमेंट करा',
    simulatePayment: 'पेमेंट सिम्युलेट करा',
    deleteNotification: 'सूचना हटवा',
    confirmDelete: 'तुम्हाला खात्री आहे का?',
    noNotifications: 'सूचना नाहीत',
    allCaughtUp: 'तुम्ही सर्व पाहिले आहे!',
    startConversation: 'संवाद सुरू करा!',
    languageChanged: 'भाषा बदलली',
    appLanguageChangedTo: 'अॅप भाषा बदलली',
    clearCache: 'कॅश साफ करा',
    clearCachePrompt: 'अॅप कॅश साफ करायचा का?',
    clear: 'साफ करा',
    cacheCleared: 'कॅश यशस्वीरित्या साफ झाली',
    pushNotifications: 'पुश सूचनां',
    sound: 'ध्वनी',
    reportIssue: 'समस्या नोंदवा',
    appName: 'Farmer Buyer Contract',
    allRightsReserved: '© 2024 सर्व हक्क राखीव',
    success: 'यशस्वी',
    error: 'त्रुटी',
    history: 'इतिहास',
    farmName: 'फार्मचे नाव',
    farmSize: 'फार्मचा आकार',
    notProvided: 'दिलेला नाही',
    sendMessage: 'संदेश पाठवा',
    aboutFarmer: 'शेतकऱ्याबद्दल',
    defaultFarmerBio: 'उच्च दर्जाची सेंद्रिय उत्पादने देणारा अनुभवी शेतकरी.',
    totalSales: 'एकूण विक्री',
    cropsListed: 'सूचीबद्ध पिके',
    customerReviews: 'ग्राहक पुनरावलोकने',
    noReviews: 'अजून पुनरावलोकने नाहीत',
    fullName: 'पूर्ण नाव',
    enterFullName: 'तुमचे पूर्ण नाव लिहा',
    phoneNumber: 'फोन नंबर',
    enterPhoneNumber: 'तुमचा फोन नंबर लिहा',
    enterLocation: 'तुमचे स्थान लिहा',
    bio: 'परिचय',
    enterBio: 'तुमच्याबद्दल सांगा',
    enterFarmName: 'फार्मचे नाव लिहा',
    enterFarmSize: 'उदा. 5 एकर',
    saveChanges: 'बदल जतन करा',
    nameRequired: 'नाव आवश्यक आहे',
    profileUpdated: 'प्रोफाईल यशस्वीरित्या अपडेट झाली'
  },
};

export const LanguageProvider = ({ children }) => {
  const { user } = useAuth();
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    loadLanguage(user?.uid);
  }, [user]);

  const loadLanguage = async (userId = null) => {
    const key = userId ? `appLanguage_${userId}` : 'appLanguage_guest';
    const savedLanguage = await AsyncStorage.getItem(key);
    const deviceLanguage = Localization.locale ? Localization.locale.split('-')[0] : 'en';
    
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    } else if (!userId) {
      // If guest, try global setting or device language
      const globalLang = await AsyncStorage.getItem('appLanguage_global');
      if (globalLang && translations[globalLang]) {
        setLanguage(globalLang);
      } else if (translations[deviceLanguage]) {
        setLanguage(deviceLanguage);
      }
    } else if (translations[deviceLanguage]) {
      setLanguage(deviceLanguage);
    }
  };

  const changeLanguage = async (lang, userId = user?.uid) => {
    if (translations[lang]) {
      setLanguage(lang);
      const key = userId ? `appLanguage_${userId}` : 'appLanguage_guest';
      await AsyncStorage.setItem(key, lang);
      if (!userId) {
        await AsyncStorage.setItem('appLanguage_global', lang);
      }
    }
  };

  const t = (key) => {
    const langDict = translations[language] || translations.en;
    return langDict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: changeLanguage,
      t,
      translations: translations[language],
      loadLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
};